// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TVFeedsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250420205743_tvAppChannels")]
    partial class tvAppChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Channel", b =>
                {
                    b.Property<int>("ChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChannelId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChannelId");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            ChannelId = 257,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "A&E US Eastern Feed HD",
                            Url = "https://tvpass.org/live/AEEast/hd"
                        },
                        new
                        {
                            ChannelId = 258,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "ABC (KABC) Los Angeles HD",
                            Url = "https://tvpass.org/live/abc-kabc-los-angeles-ca/hd"
                        },
                        new
                        {
                            ChannelId = 259,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "ABC (WABC) New York, NY HD",
                            Url = "https://tvpass.org/live/WABCDT1/hd"
                        },
                        new
                        {
                            ChannelId = 260,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "ACC Network HD",
                            Url = "https://tvpass.org/live/ACCNetwork/hd"
                        },
                        new
                        {
                            ChannelId = 261,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Altitude Sports Denver HD",
                            Url = "https://tvpass.org/live/altitude-sports-denver/hd"
                        },
                        new
                        {
                            ChannelId = 262,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "AMC Eastern Feed HD",
                            Url = "https://tvpass.org/live/AMCEast/hd"
                        },
                        new
                        {
                            ChannelId = 263,
                            Category = "History",
                            Icon = "⏳",
                            Name = "American Heroes Channel HD",
                            Url = "https://tvpass.org/live/AmericanHeroesChannel/hd"
                        },
                        new
                        {
                            ChannelId = 264,
                            Category = "Animals",
                            Icon = "🐶",
                            Name = "Animal Planet US East HD",
                            Url = "https://tvpass.org/live/AnimalPlanetEast/hd"
                        },
                        new
                        {
                            ChannelId = 265,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "BBC America East HD",
                            Url = "https://tvpass.org/live/BBCAmericaEast/hd"
                        },
                        new
                        {
                            ChannelId = 266,
                            Category = "News",
                            Icon = "📰",
                            Name = "BBC News North America HD HD",
                            Url = "https://tvpass.org/live/BBCWorldNewsNorthAmerica/hd"
                        },
                        new
                        {
                            ChannelId = 267,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "BET Eastern Feed HD",
                            Url = "https://tvpass.org/live/BETEast/hd"
                        },
                        new
                        {
                            ChannelId = 268,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "BET Her HD",
                            Url = "https://tvpass.org/live/BETHerEast/hd"
                        },
                        new
                        {
                            ChannelId = 269,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Big Ten Network HD",
                            Url = "https://tvpass.org/live/BTN/hd"
                        },
                        new
                        {
                            ChannelId = 270,
                            Category = "News",
                            Icon = "📰",
                            Name = "Bloomberg TV USA HD",
                            Url = "https://tvpass.org/live/BloombergTV/hd"
                        },
                        new
                        {
                            ChannelId = 271,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Boomerang HD",
                            Url = "https://tvpass.org/live/Boomerang/hd"
                        },
                        new
                        {
                            ChannelId = 272,
                            Category = "Reality",
                            Icon = "📺",
                            Name = "Bravo USA Eastern Feed HD",
                            Url = "https://tvpass.org/live/BravoEast/hd"
                        },
                        new
                        {
                            ChannelId = 273,
                            Category = "News",
                            Icon = "📰",
                            Name = "C-SPAN HD",
                            Url = "https://tvpass.org/live/CSPAN/hd"
                        },
                        new
                        {
                            ChannelId = 274,
                            Category = "News",
                            Icon = "📰",
                            Name = "C-SPAN 2 HD",
                            Url = "https://tvpass.org/live/CSPAN2/hd"
                        },
                        new
                        {
                            ChannelId = 275,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Cartoon Network USA Eastern Feed HD",
                            Url = "https://tvpass.org/live/CartoonNetworkEast/hd"
                        },
                        new
                        {
                            ChannelId = 276,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "CBS (KCBS) Los Angeles HD",
                            Url = "https://tvpass.org/live/cbs-kcbs-los-angeles-ca/hd"
                        },
                        new
                        {
                            ChannelId = 277,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "CBS (WCBS) New York, NY HD",
                            Url = "https://tvpass.org/live/WCBSDT1/hd"
                        },
                        new
                        {
                            ChannelId = 278,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "CBS Sports Network USA HD",
                            Url = "https://tvpass.org/live/CBSSportsNetworkUSA/hd"
                        },
                        new
                        {
                            ChannelId = 279,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Chicago Sports Network HD",
                            Url = "https://tvpass.org/live/chicago-sports-network/hd"
                        },
                        new
                        {
                            ChannelId = 280,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Cinemax Eastern Feed HD",
                            Url = "https://tvpass.org/live/CinemaxEast/hd"
                        },
                        new
                        {
                            ChannelId = 281,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "CMT US Eastern Feed HD",
                            Url = "https://tvpass.org/live/CMTEast/hd"
                        },
                        new
                        {
                            ChannelId = 282,
                            Category = "News",
                            Icon = "📰",
                            Name = "CNBC USA HD",
                            Url = "https://tvpass.org/live/CNBC/hd"
                        },
                        new
                        {
                            ChannelId = 283,
                            Category = "News",
                            Icon = "📰",
                            Name = "CNN US HD",
                            Url = "https://tvpass.org/live/CNN/hd"
                        },
                        new
                        {
                            ChannelId = 284,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "Comedy Central (US) Eastern Feed HD",
                            Url = "https://tvpass.org/live/ComedyCentralEast/hd"
                        },
                        new
                        {
                            ChannelId = 285,
                            Category = "Crime",
                            Icon = "🕵️",
                            Name = "Crime & Investigation Network USA HD HD",
                            Url = "https://tvpass.org/live/CrimePlusInvestigation/hd"
                        },
                        new
                        {
                            ChannelId = 286,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "CW (KFMB-TV2) San Diego HD",
                            Url = "https://tvpass.org/live/cw-kfmbtv2-san-diego-ca/hd"
                        },
                        new
                        {
                            ChannelId = 287,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "CW (WDCW) District of Columbia HD",
                            Url = "https://tvpass.org/live/cw-wdcw-district-of-columbia/hd"
                        },
                        new
                        {
                            ChannelId = 288,
                            Category = "Travel",
                            Icon = "✈️",
                            Name = "Destination America HD",
                            Url = "https://tvpass.org/live/DestinationAmerica/hd"
                        },
                        new
                        {
                            ChannelId = 289,
                            Category = "Documentary",
                            Icon = "🌍",
                            Name = "Discovery Channel (US) Eastern Feed HD",
                            Url = "https://tvpass.org/live/DiscoveryChannelEast/hd"
                        },
                        new
                        {
                            ChannelId = 290,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Discovery Family Channel HD",
                            Url = "https://tvpass.org/live/DiscoveryFamily/hd"
                        },
                        new
                        {
                            ChannelId = 291,
                            Category = "Lifestyle",
                            Icon = "🏇",
                            Name = "Discovery Life Channel HD",
                            Url = "https://tvpass.org/live/DiscoveryLife/hd"
                        },
                        new
                        {
                            ChannelId = 292,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Disney Eastern Feed HD",
                            Url = "https://tvpass.org/live/DisneyChannelEast/hd"
                        },
                        new
                        {
                            ChannelId = 293,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Disney Junior USA East HD",
                            Url = "https://tvpass.org/live/DisneyJuniorEast/hd"
                        },
                        new
                        {
                            ChannelId = 294,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Disney XD USA Eastern Feed HD",
                            Url = "https://tvpass.org/live/DisneyXDEast/hd"
                        },
                        new
                        {
                            ChannelId = 295,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "E! Entertainment USA Eastern Feed HD",
                            Url = "https://tvpass.org/live/EEast/hd"
                        },
                        new
                        {
                            ChannelId = 296,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "ESPN HD",
                            Url = "https://tvpass.org/live/ESPN/hd"
                        },
                        new
                        {
                            ChannelId = 297,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "ESPN Deportes HD",
                            Url = "https://tvpass.org/live/espn-deportes/hd"
                        },
                        new
                        {
                            ChannelId = 298,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "ESPN News HD",
                            Url = "https://tvpass.org/live/ESPNews/hd"
                        },
                        new
                        {
                            ChannelId = 299,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "ESPN U HD",
                            Url = "https://tvpass.org/live/ESPNU/hd"
                        },
                        new
                        {
                            ChannelId = 300,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "ESPN2 HD",
                            Url = "https://tvpass.org/live/ESPN2/hd"
                        },
                        new
                        {
                            ChannelId = 301,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Indiana HD",
                            Url = "https://tvpass.org/live/fanduel-sports-indiana/hd"
                        },
                        new
                        {
                            ChannelId = 302,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network Detroit HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-detroit-hd/hd"
                        },
                        new
                        {
                            ChannelId = 303,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network Florida HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-florida/hd"
                        },
                        new
                        {
                            ChannelId = 304,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network Great Lakes HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-great-lakes/hd"
                        },
                        new
                        {
                            ChannelId = 305,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network North HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-north/hd"
                        },
                        new
                        {
                            ChannelId = 306,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network Ohio Cleveland HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-ohio-cleveland/hd"
                        },
                        new
                        {
                            ChannelId = 307,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network Oklahoma HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-oklahoma/hd"
                        },
                        new
                        {
                            ChannelId = 308,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network San Diego HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-san-diego/hd"
                        },
                        new
                        {
                            ChannelId = 309,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network Socal HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-socal/hd"
                        },
                        new
                        {
                            ChannelId = 310,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network South Carolinas HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-south-carolinas/hd"
                        },
                        new
                        {
                            ChannelId = 311,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network South Tennessee HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-south-tennessee-usa/hd"
                        },
                        new
                        {
                            ChannelId = 312,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network West HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-west/hd"
                        },
                        new
                        {
                            ChannelId = 313,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Network Wisconsin HD",
                            Url = "https://tvpass.org/live/fanduel-sports-network-wisconsin/hd"
                        },
                        new
                        {
                            ChannelId = 314,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Southeast Georgia HD",
                            Url = "https://tvpass.org/live/fanduel-sports-southeast-georgia/hd"
                        },
                        new
                        {
                            ChannelId = 315,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Southeast North Carolina HD",
                            Url = "https://tvpass.org/live/fanduel-sports-southeast-north-carolina/hd"
                        },
                        new
                        {
                            ChannelId = 316,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Southeast South Carolina HD",
                            Url = "https://tvpass.org/live/fanduel-sports-southeast-south-carolina/hd"
                        },
                        new
                        {
                            ChannelId = 317,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Southeast Tennessee Nashville HD",
                            Url = "https://tvpass.org/live/fanduel-sports-southeast-tennessee-nashville/hd"
                        },
                        new
                        {
                            ChannelId = 318,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Sun HD",
                            Url = "https://tvpass.org/live/fanduel-sports-sun/hd"
                        },
                        new
                        {
                            ChannelId = 319,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fanduel Sports Tennessee East HD",
                            Url = "https://tvpass.org/live/fanduel-sports-tennessee-east/hd"
                        },
                        new
                        {
                            ChannelId = 320,
                            Category = "Food",
                            Icon = "🍳",
                            Name = "Food Network USA Eastern Feed HD",
                            Url = "https://tvpass.org/live/FoodNetworkEast/hd"
                        },
                        new
                        {
                            ChannelId = 321,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "FOX (KTTV) Los Angeles HD",
                            Url = "https://tvpass.org/live/fox-kttv-los-angeles-ca/hd"
                        },
                        new
                        {
                            ChannelId = 322,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "FOX (WNYW) New York, NY HD",
                            Url = "https://tvpass.org/live/WNYWDT1/hd"
                        },
                        new
                        {
                            ChannelId = 323,
                            Category = "News",
                            Icon = "📰",
                            Name = "Fox Business HD",
                            Url = "https://tvpass.org/live/FoxBusiness/hd"
                        },
                        new
                        {
                            ChannelId = 324,
                            Category = "News",
                            Icon = "📰",
                            Name = "Fox News HD",
                            Url = "https://tvpass.org/live/FoxNewsChannel/hd"
                        },
                        new
                        {
                            ChannelId = 325,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fox Sports 1 HD",
                            Url = "https://tvpass.org/live/FoxSports1/hd"
                        },
                        new
                        {
                            ChannelId = 326,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Fox Sports 2 HD",
                            Url = "https://tvpass.org/live/FoxSports2/hd"
                        },
                        new
                        {
                            ChannelId = 327,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "Freeform East Feed HD",
                            Url = "https://tvpass.org/live/FreeformEast/hd"
                        },
                        new
                        {
                            ChannelId = 328,
                            Category = "Music",
                            Icon = "🎵",
                            Name = "FUSE TV Eastern feed HD",
                            Url = "https://tvpass.org/live/FuseEast/hd"
                        },
                        new
                        {
                            ChannelId = 329,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "FX Movie Channel HD",
                            Url = "https://tvpass.org/live/FXMovieChannel/hd"
                        },
                        new
                        {
                            ChannelId = 330,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "FX Networks East Coast HD",
                            Url = "https://tvpass.org/live/FXEast/hd"
                        },
                        new
                        {
                            ChannelId = 331,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "FXX USA Eastern HD",
                            Url = "https://tvpass.org/live/FXXEast/hd"
                        },
                        new
                        {
                            ChannelId = 332,
                            Category = "Lifestyle",
                            Icon = "🏇",
                            Name = "FYI USA Eastern HD",
                            Url = "https://tvpass.org/live/FYIEast/hd"
                        },
                        new
                        {
                            ChannelId = 333,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "Game Show Network East HD",
                            Url = "https://tvpass.org/live/game-show-network-east/hd"
                        },
                        new
                        {
                            ChannelId = 334,
                            Category = "Golf",
                            Icon = "⚽",
                            Name = "Golf Channel USA HD",
                            Url = "https://tvpass.org/live/GolfChannel/hd"
                        },
                        new
                        {
                            ChannelId = 335,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Hallmark Eastern Feed HD",
                            Url = "https://tvpass.org/live/HallmarkChannelEast/hd"
                        },
                        new
                        {
                            ChannelId = 336,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Hallmark Family HD HD",
                            Url = "https://tvpass.org/live/HallmarkDrama/hd"
                        },
                        new
                        {
                            ChannelId = 337,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Hallmark Mystery Eastern HD HD",
                            Url = "https://tvpass.org/live/HallmarkMoviesMysteriesEast/hd"
                        },
                        new
                        {
                            ChannelId = 338,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "HBO Eastern Feed HD",
                            Url = "https://tvpass.org/live/HBOEast/hd"
                        },
                        new
                        {
                            ChannelId = 339,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "HBO 2 Eastern Feed HD",
                            Url = "https://tvpass.org/live/HBO2East/hd"
                        },
                        new
                        {
                            ChannelId = 340,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "HBO Comedy HD East HD",
                            Url = "https://tvpass.org/live/HBOComedyEast/hd"
                        },
                        new
                        {
                            ChannelId = 341,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "HBO Family Eastern Feed HD",
                            Url = "https://tvpass.org/live/HBOFamilyEast/hd"
                        },
                        new
                        {
                            ChannelId = 342,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "HBO Signature (HBO 3) Eastern HD",
                            Url = "https://tvpass.org/live/HBOSignatureEast/hd"
                        },
                        new
                        {
                            ChannelId = 343,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "HBO Zone HD East HD",
                            Url = "https://tvpass.org/live/HBOZoneEast/hd"
                        },
                        new
                        {
                            ChannelId = 344,
                            Category = "Home",
                            Icon = "🏠",
                            Name = "HGTV USA Eastern Feed HD",
                            Url = "https://tvpass.org/live/HGTVEast/hd"
                        },
                        new
                        {
                            ChannelId = 345,
                            Category = "History",
                            Icon = "⏳",
                            Name = "History Channel US Eastern Feed HD",
                            Url = "https://tvpass.org/live/HistoryEast/hd"
                        },
                        new
                        {
                            ChannelId = 346,
                            Category = "News",
                            Icon = "📰",
                            Name = "HLN HD",
                            Url = "https://tvpass.org/live/HLN/hd"
                        },
                        new
                        {
                            ChannelId = 347,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Independent Film Channel US HD",
                            Url = "https://tvpass.org/live/IFCEast/hd"
                        },
                        new
                        {
                            ChannelId = 348,
                            Category = "Crime",
                            Icon = "🕵️",
                            Name = "Investigation Discovery USA Eastern HD",
                            Url = "https://tvpass.org/live/InvestigationDiscoveryEast/hd"
                        },
                        new
                        {
                            ChannelId = 349,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "ION Eastern Feed HD",
                            Url = "https://tvpass.org/live/IONTVEast/hd"
                        },
                        new
                        {
                            ChannelId = 350,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Lifetime Movies East HD",
                            Url = "https://tvpass.org/live/LifetimeMoviesEast/hd"
                        },
                        new
                        {
                            ChannelId = 351,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "Lifetime Network US Eastern Feed HD",
                            Url = "https://tvpass.org/live/LifetimeEast/hd"
                        },
                        new
                        {
                            ChannelId = 352,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "LOGO East HD",
                            Url = "https://tvpass.org/live/LogoEast/hd"
                        },
                        new
                        {
                            ChannelId = 353,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Marquee Sports Network HD",
                            Url = "https://tvpass.org/live/marquee-sports-network/hd"
                        },
                        new
                        {
                            ChannelId = 354,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "MeTV Toons (WJLP2) New Jersey HD",
                            Url = "https://tvpass.org/live/metv-toons/hd"
                        },
                        new
                        {
                            ChannelId = 355,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "MeTV Wjlp New Jerseynew York HD",
                            Url = "https://tvpass.org/live/metv-wjlp-new-jerseynew-york/hd"
                        },
                        new
                        {
                            ChannelId = 356,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Midatlantic Sports Network HD",
                            Url = "https://tvpass.org/live/midatlantic-sports-network/hd"
                        },
                        new
                        {
                            ChannelId = 357,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "MLB Network HD",
                            Url = "https://tvpass.org/live/MLBNetwork/hd"
                        },
                        new
                        {
                            ChannelId = 358,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Monumental Sports Network HD",
                            Url = "https://tvpass.org/live/monumental-sports-network/hd"
                        },
                        new
                        {
                            ChannelId = 359,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "MoreMax Eastern HD",
                            Url = "https://tvpass.org/live/MoreMaxEast/hd"
                        },
                        new
                        {
                            ChannelId = 360,
                            Category = "Automotive",
                            Icon = "🏎️",
                            Name = "Motor Trend HD HD",
                            Url = "https://tvpass.org/live/Motortrend/hd"
                        },
                        new
                        {
                            ChannelId = 361,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "MovieMax (Max 6) East HD",
                            Url = "https://tvpass.org/live/MovieMaxEast/hd"
                        },
                        new
                        {
                            ChannelId = 362,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "MSG Madison Square Gardens HD",
                            Url = "https://tvpass.org/live/msg-madison-square-gardens/hd"
                        },
                        new
                        {
                            ChannelId = 363,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "MSG Plus HD",
                            Url = "https://tvpass.org/live/msg-plus/hd"
                        },
                        new
                        {
                            ChannelId = 364,
                            Category = "News",
                            Icon = "📰",
                            Name = "MSNBC USA HD",
                            Url = "https://tvpass.org/live/MSNBC/hd"
                        },
                        new
                        {
                            ChannelId = 365,
                            Category = "Music",
                            Icon = "🎵",
                            Name = "MTV 2 East HD",
                            Url = "https://tvpass.org/live/mtv-2-east/hd"
                        },
                        new
                        {
                            ChannelId = 366,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "MTV USA Eastern Feed HD",
                            Url = "https://tvpass.org/live/MTVEast/hd"
                        },
                        new
                        {
                            ChannelId = 367,
                            Category = "Documentary",
                            Icon = "🌍",
                            Name = "National Geographic US Eastern HD",
                            Url = "https://tvpass.org/live/NationalGeographicEast/hd"
                        },
                        new
                        {
                            ChannelId = 368,
                            Category = "Animals",
                            Icon = "🐶",
                            Name = "National Geographic Wild HD",
                            Url = "https://tvpass.org/live/NationalGeographicWildEast/hd"
                        },
                        new
                        {
                            ChannelId = 369,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "NBA TV USA HD",
                            Url = "https://tvpass.org/live/NBATV/hd"
                        },
                        new
                        {
                            ChannelId = 370,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "NBC (KNBC) Los Angeles HD",
                            Url = "https://tvpass.org/live/nbc-knbc-los-angeles-ca/hd"
                        },
                        new
                        {
                            ChannelId = 371,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "NBC (WNBC) New York, NY HD",
                            Url = "https://tvpass.org/live/WNBCDT1/hd"
                        },
                        new
                        {
                            ChannelId = 372,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "NBC Sports Bay Area HD",
                            Url = "https://tvpass.org/live/nbc-sports-bay-area/hd"
                        },
                        new
                        {
                            ChannelId = 373,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "NBC Sports Boston HD",
                            Url = "https://tvpass.org/live/nbc-sports-boston/hd"
                        },
                        new
                        {
                            ChannelId = 374,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "NBC Sports California HD",
                            Url = "https://tvpass.org/live/nbc-sports-california/hd"
                        },
                        new
                        {
                            ChannelId = 375,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "NBC Sports Philadelphia HD",
                            Url = "https://tvpass.org/live/nbc-sports-philadelphia/hd"
                        },
                        new
                        {
                            ChannelId = 376,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "New England Sports Network HD",
                            Url = "https://tvpass.org/live/new-england-sports-network/hd"
                        },
                        new
                        {
                            ChannelId = 377,
                            Category = "News",
                            Icon = "📰",
                            Name = "NewsMax TV HD",
                            Url = "https://tvpass.org/live/NewsmaxTV/hd"
                        },
                        new
                        {
                            ChannelId = 378,
                            Category = "Football",
                            Icon = "⚽",
                            Name = "NFL Network HD",
                            Url = "https://tvpass.org/live/NFLNetwork/hd"
                        },
                        new
                        {
                            ChannelId = 379,
                            Category = "Football",
                            Icon = "⚽",
                            Name = "NFL RedZone HD",
                            Url = "https://tvpass.org/live/NFLRedZone/hd"
                        },
                        new
                        {
                            ChannelId = 380,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "NHL Network USA HD",
                            Url = "https://tvpass.org/live/NHLNetwork/hd"
                        },
                        new
                        {
                            ChannelId = 381,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Nick Jr. East HD",
                            Url = "https://tvpass.org/live/NickJrEast/hd"
                        },
                        new
                        {
                            ChannelId = 382,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Nickelodeon USA East Feed HD",
                            Url = "https://tvpass.org/live/NickelodeonEast/hd"
                        },
                        new
                        {
                            ChannelId = 383,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Nicktoons East HD",
                            Url = "https://tvpass.org/live/NicktoonsEast/hd"
                        },
                        new
                        {
                            ChannelId = 384,
                            Category = "Lifestyle",
                            Icon = "🏇",
                            Name = "Oprah Winfrey Network USA Eastern HD",
                            Url = "https://tvpass.org/live/OWNEast/hd"
                        },
                        new
                        {
                            ChannelId = 385,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Outdoor Channel US HD",
                            Url = "https://tvpass.org/live/OutdoorChannel/hd"
                        },
                        new
                        {
                            ChannelId = 386,
                            Category = "Crime",
                            Icon = "🕵️",
                            Name = "Oxygen Eastern Feed HD",
                            Url = "https://tvpass.org/live/OxygenEast/hd"
                        },
                        new
                        {
                            ChannelId = 387,
                            Category = "Documentary",
                            Icon = "🌍",
                            Name = "PBS (WNET) New York, NY HD",
                            Url = "https://tvpass.org/live/WNET/hd"
                        },
                        new
                        {
                            ChannelId = 388,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "ReelzChannel HD",
                            Url = "https://tvpass.org/live/Reelz/hd"
                        },
                        new
                        {
                            ChannelId = 389,
                            Category = "Documentary",
                            Icon = "🌍",
                            Name = "Science HD",
                            Url = "https://tvpass.org/live/Science/hd"
                        },
                        new
                        {
                            ChannelId = 390,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "SEC Network HD",
                            Url = "https://tvpass.org/live/SECN/hd"
                        },
                        new
                        {
                            ChannelId = 391,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Showtime Eastern Feed HD",
                            Url = "https://tvpass.org/live/ShowtimeEast/hd"
                        },
                        new
                        {
                            ChannelId = 392,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Showtime 2 Eastern HD",
                            Url = "https://tvpass.org/live/Showtime2East/hd"
                        },
                        new
                        {
                            ChannelId = 393,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "SNY Sportsnet New York Comcast HD",
                            Url = "https://tvpass.org/live/sny-sportsnet-new-york-comcast/hd"
                        },
                        new
                        {
                            ChannelId = 394,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Space City Home Network HD",
                            Url = "https://tvpass.org/live/space-city-home-network/hd"
                        },
                        new
                        {
                            ChannelId = 395,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Spectrum SportsNet LA HD",
                            Url = "https://tvpass.org/live/spectrum-sportsnet-la/hd"
                        },
                        new
                        {
                            ChannelId = 396,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Spectrum Sportsnet Lakers HD",
                            Url = "https://tvpass.org/live/spectrum-sportsnet/hd"
                        },
                        new
                        {
                            ChannelId = 397,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Sportsnet (East) HD",
                            Url = "https://tvpass.org/live/sportsnet-east/hd"
                        },
                        new
                        {
                            ChannelId = 398,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Sportsnet 360 HD",
                            Url = "https://tvpass.org/live/sportsnet-360/hd"
                        },
                        new
                        {
                            ChannelId = 399,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Sportsnet One HD",
                            Url = "https://tvpass.org/live/sportsnet-one/hd"
                        },
                        new
                        {
                            ChannelId = 400,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Sportsnet Ontario HD",
                            Url = "https://tvpass.org/live/sportsnet-ontario/hd"
                        },
                        new
                        {
                            ChannelId = 401,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Sportsnet Pacific HD",
                            Url = "https://tvpass.org/live/sportsnet-pacific/hd"
                        },
                        new
                        {
                            ChannelId = 402,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Sportsnet Pittsburgh HD",
                            Url = "https://tvpass.org/live/sportsnet-pittsburgh/hd"
                        },
                        new
                        {
                            ChannelId = 403,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Sportsnet West HD",
                            Url = "https://tvpass.org/live/sportsnet-west/hd"
                        },
                        new
                        {
                            ChannelId = 404,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Starz Eastern HD",
                            Url = "https://tvpass.org/live/StarzEast/hd"
                        },
                        new
                        {
                            ChannelId = 405,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "SundanceTV USA East HD",
                            Url = "https://tvpass.org/live/SundanceTVEast/hd"
                        },
                        new
                        {
                            ChannelId = 406,
                            Category = "Sci-Fi",
                            Icon = "👽",
                            Name = "Syfy Eastern Feed HD",
                            Url = "https://tvpass.org/live/SyfyEast/hd"
                        },
                        new
                        {
                            ChannelId = 407,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "TBS East HD",
                            Url = "https://tvpass.org/live/TBSEast/hd"
                        },
                        new
                        {
                            ChannelId = 408,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "TeenNick Eastern HD",
                            Url = "https://tvpass.org/live/TeenNickEast/hd"
                        },
                        new
                        {
                            ChannelId = 409,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "Telemundo Eastern Feed HD",
                            Url = "https://tvpass.org/live/TelemundoEast/hd"
                        },
                        new
                        {
                            ChannelId = 410,
                            Category = "Food",
                            Icon = "🍳",
                            Name = "The Cooking Channel HD",
                            Url = "https://tvpass.org/live/CookingChannel/hd"
                        },
                        new
                        {
                            ChannelId = 411,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "The Tennis Channel HD",
                            Url = "https://tvpass.org/live/TennisChannel/hd"
                        },
                        new
                        {
                            ChannelId = 412,
                            Category = "News",
                            Icon = "📰",
                            Name = "The Weather Channel HD",
                            Url = "https://tvpass.org/live/TheWeatherChannel/hd"
                        },
                        new
                        {
                            ChannelId = 413,
                            Category = "Reality",
                            Icon = "📺",
                            Name = "TLC USA Eastern HD",
                            Url = "https://tvpass.org/live/TLCEast/hd"
                        },
                        new
                        {
                            ChannelId = 414,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "TMC (US) Eastern Feed HD",
                            Url = "https://tvpass.org/live/TheMovieChannelEast/hd"
                        },
                        new
                        {
                            ChannelId = 415,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "TNT Eastern Feed HD",
                            Url = "https://tvpass.org/live/TNTEast/hd"
                        },
                        new
                        {
                            ChannelId = 416,
                            Category = "Travel",
                            Icon = "✈️",
                            Name = "Travel US East HD",
                            Url = "https://tvpass.org/live/TravelChannelEast/hd"
                        },
                        new
                        {
                            ChannelId = 417,
                            Category = "Reality",
                            Icon = "📺",
                            Name = "truTV USA Eastern HD",
                            Url = "https://tvpass.org/live/truTVEast/hd"
                        },
                        new
                        {
                            ChannelId = 418,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "TSN1 HD",
                            Url = "https://tvpass.org/live/tsn1/hd"
                        },
                        new
                        {
                            ChannelId = 419,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "TSN2 HD",
                            Url = "https://tvpass.org/live/tsn2/hd"
                        },
                        new
                        {
                            ChannelId = 420,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "TSN3 HD",
                            Url = "https://tvpass.org/live/tsn3/hd"
                        },
                        new
                        {
                            ChannelId = 421,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "TSN4 HD",
                            Url = "https://tvpass.org/live/tsn4/hd"
                        },
                        new
                        {
                            ChannelId = 422,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "TSN5 HD",
                            Url = "https://tvpass.org/live/tsn5/hd"
                        },
                        new
                        {
                            ChannelId = 423,
                            Category = "Movies",
                            Icon = "🎬",
                            Name = "Turner Classic Movies USA HD",
                            Url = "https://tvpass.org/live/TCMEast/hd"
                        },
                        new
                        {
                            ChannelId = 424,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "TV Land Eastern HD",
                            Url = "https://tvpass.org/live/tv-land-eastern/hd"
                        },
                        new
                        {
                            ChannelId = 425,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "TV One HD",
                            Url = "https://tvpass.org/live/TVOne/hd"
                        },
                        new
                        {
                            ChannelId = 426,
                            Category = "Kids",
                            Icon = "👶",
                            Name = "Universal Kids HD",
                            Url = "https://tvpass.org/live/UniversalKidsEast/hd"
                        },
                        new
                        {
                            ChannelId = 427,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "Univision Eastern Feed HD",
                            Url = "https://tvpass.org/live/UnivisionEast/hd"
                        },
                        new
                        {
                            ChannelId = 428,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "USA Network East Feed HD",
                            Url = "https://tvpass.org/live/USANetworkEast/hd"
                        },
                        new
                        {
                            ChannelId = 429,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "VH1 Eastern Feed HD",
                            Url = "https://tvpass.org/live/VH1East/hd"
                        },
                        new
                        {
                            ChannelId = 430,
                            Category = "Documentary",
                            Icon = "🌍",
                            Name = "VICE HD",
                            Url = "https://tvpass.org/live/VICETV/hd"
                        },
                        new
                        {
                            ChannelId = 431,
                            Category = "Reality",
                            Icon = "📺",
                            Name = "WE (Women's Entertainment) Eastern HD",
                            Url = "https://tvpass.org/live/WeTVEast/hd"
                        },
                        new
                        {
                            ChannelId = 432,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "WPIX New York (SUPERSTATION) HD",
                            Url = "https://tvpass.org/live/WPIX/hd"
                        },
                        new
                        {
                            ChannelId = 433,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Yes Network HD",
                            Url = "https://tvpass.org/live/yes-network/hd"
                        },
                        new
                        {
                            ChannelId = 434,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Memphis Grizzlies @ Oklahoma City Thunder (04/20 1:10 PM ET) HD",
                            Url = "https://tvpass.org/live/WABCDT1/hd"
                        },
                        new
                        {
                            ChannelId = 435,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Minnesota Twins @ Atlanta Braves (04/20 1:35 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-28/hd"
                        },
                        new
                        {
                            ChannelId = 436,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Cincinnati Reds @ Baltimore Orioles (04/20 1:35 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-17/hd"
                        },
                        new
                        {
                            ChannelId = 437,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Chicago White Sox @ Boston Red Sox (04/20 1:36 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-22/hd"
                        },
                        new
                        {
                            ChannelId = 438,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Cleveland Guardians @ Pittsburgh Pirates (04/20 1:36 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-26/hd"
                        },
                        new
                        {
                            ChannelId = 439,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Miami Marlins @ Philadelphia Phillies (04/20 1:36 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-18/hd"
                        },
                        new
                        {
                            ChannelId = 440,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Seattle Mariners @ Toronto Blue Jays (04/20 1:38 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-12/hd"
                        },
                        new
                        {
                            ChannelId = 441,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Kansas City Royals @ Detroit Tigers (04/20 1:41 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-21/hd"
                        },
                        new
                        {
                            ChannelId = 442,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "St. Louis Cardinals @ New York Mets (04/20 1:41 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-24/hd"
                        },
                        new
                        {
                            ChannelId = 443,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "New York Yankees @ Tampa Bay Rays (04/20 1:41 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-11/hd"
                        },
                        new
                        {
                            ChannelId = 444,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Oakland Athletics @ Milwaukee Brewers (04/20 2:11 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-16/hd"
                        },
                        new
                        {
                            ChannelId = 445,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Arizona Diamondbacks @ Chicago Cubs (04/20 2:21 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-23/hd"
                        },
                        new
                        {
                            ChannelId = 446,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Los Angeles Dodgers @ Texas Rangers (04/20 2:36 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-13/hd"
                        },
                        new
                        {
                            ChannelId = 447,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "New Jersey Devils @ Carolina Hurricanes (04/20 3:10 PM ET) HD",
                            Url = "https://tvpass.org/live/sportsnet-east/hd"
                        },
                        new
                        {
                            ChannelId = 448,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Washington Nationals @ Colorado Rockies (04/20 3:11 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-25/hd"
                        },
                        new
                        {
                            ChannelId = 449,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Orlando Magic @ Boston Celtics (04/20 3:30 PM ET) HD",
                            Url = "https://tvpass.org/live/WABCDT1/hd"
                        },
                        new
                        {
                            ChannelId = 450,
                            Category = "Entertainment",
                            Icon = "😂",
                            Name = "WrestleMania 41 Sunday (04/20 4:00 PM ET) HD",
                            Url = "https://tvpass.org/live/PPV01/hd"
                        },
                        new
                        {
                            ChannelId = 451,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "San Francisco Giants @ Los Angeles Angels (04/20 4:07 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-29/hd"
                        },
                        new
                        {
                            ChannelId = 452,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "San Diego Padres @ Houston Astros (04/20 7:10 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-06/hd"
                        },
                        new
                        {
                            ChannelId = 453,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Miami Heat @ Cleveland Cavaliers (04/20 7:10 PM ET) HD",
                            Url = "https://tvpass.org/live/TNTEast/hd"
                        },
                        new
                        {
                            ChannelId = 454,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Ottawa Senators @ Toronto Maple Leafs (04/20 7:10 PM ET) HD",
                            Url = "https://tvpass.org/live/sportsnet-east/hd"
                        },
                        new
                        {
                            ChannelId = 455,
                            Category = "Baseball",
                            Icon = "⚾",
                            Name = "Washington Nationals @ Colorado Rockies (04/20 8:10 PM ET) HD",
                            Url = "https://tvpass.org/live/mlb-25/hd"
                        },
                        new
                        {
                            ChannelId = 456,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Golden State Warriors @ Houston Rockets (04/20 9:30 PM ET) HD",
                            Url = "https://tvpass.org/live/TNTEast/hd"
                        },
                        new
                        {
                            ChannelId = 457,
                            Category = "Sports",
                            Icon = "⚽",
                            Name = "Minnesota Wild @ Vegas Golden Knights (04/20 10:10 PM ET) HD",
                            Url = "https://tvpass.org/live/sportsnet-east/hd"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
