using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace TVFeedsApi.Migrations
{
    /// <inheritdoc />
    public partial class Initial : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Channels",
                columns: table => new
                {
                    ChannelId = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Name = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Url = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Category = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Icon = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Channels", x => x.ChannelId);
                });

            migrationBuilder.InsertData(
                table: "Channels",
                columns: new[] { "ChannelId", "Category", "Icon", "Name", "Url" },
                values: new object[,]
                {
                    { 1, "Movies", "🎬", "Action Hollywood Movies", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01076-lightningintern-actionhollywood-samsungnz/playlist.m3u8" },
                    { 2, "News", "📰", "Bloomberg Quicktake", "https://bloomberg-quicktake-4-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 3, "News", "📰", "Bloomberg TV", "https://bloomberg-bloomberg-2-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 4, "Movies", "🎬", "Bounty", "https://bountyfilms-bounty-1-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 5, "Movies", "🎬", "CineView", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01076-lightningintern-rialto-samsungnz/playlist.m3u8" },
                    { 6, "Music", "🎵", "Clubbing TV", "https://clubbingtv-samsungnz.amagi.tv/playlist.m3u8" },
                    { 7, "Entertainment", "😂", "Drybar Comedy", "https://drybar-drybarcomedy-1-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 8, "Sci-Fi", "👽", "Dust", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00219-gunpowdersky-dustintlnz-samsungnz/playlist.m3u8" },
                    { 9, "News", "📰", "EuroNews", "https://euronews-euronews-world-1-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 10, "News", "📰", "GB News", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01076-lightningintern-gbnewsnz-samsungnz/playlist.m3u8" },
                    { 11, "Food", "🍳", "Gusto TV", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01077-gustoworldwidem-gustotvnz-samsungnz/playlist.m3u8" },
                    { 12, "Lifestyle", "🏇", "Horse and Country Free", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00810-horsecountrytvl-hncfreenz-samsungnz/playlist.m3u8" },
                    { 13, "Entertainment", "🎭", "Introuble", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00861-terninternation-introublenz-samsungnz/playlist.m3u8" },
                    { 14, "Entertainment", "🎭", "InWonder", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00861-terninternation-inwondernz-samsungnz/playlist.m3u8" },
                    { 15, "Entertainment", "🎥", "Made in Hollywood", "https://connection3-ent-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 16, "Documentary", "🌍", "Magellen TV", "https://magellantv-3-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 17, "Automotive", "🏎️", "Motorvision.TV", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01329-otterainc-motorvisionnz-samsungnz/playlist.m3u8" },
                    { 18, "Entertainment", "👀", "Nosey", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00514-noseybaxterllc-noseyintlnz-samsungnz/playlist.m3u8" },
                    { 19, "Music", "🎵", "Now 70's", "https://lightning-now70s-samsungnz.amagi.tv/playlist.m3u8" },
                    { 20, "Music", "🎵", "Now 80's", "https://lightning-now80s-samsungnz.amagi.tv/playlist.m3u8" },
                    { 21, "Music", "🎸", "NOW Rock", "https://lightning-now90s-samsungnz.amagi.tv/playlist.m3u8" },
                    { 22, "Outdoor", "🌲", "Outdoor Channel", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00718-outdoorchannela-outdoortvnz-samsungnz/playlist.m3u8" },
                    { 23, "Animals", "🐶", "Pet Club TV", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01076-lightningintern-petclub-samsungnz/playlist.m3u8" },
                    { 24, "Entertainment", "💓", "Pulse TV", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01076-lightningintern-pulse-samsungnz/playlist.m3u8" },
                    { 25, "Crime", "🕵️", "Real Crime", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00426-littledotstudio-realcrimebetanz-samsungnz/playlist.m3u8" },
                    { 26, "Reality", "📺", "Real Life", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00426-littledotstudio-reallifenz-samsungnz/playlist.m3u8" },
                    { 27, "Documentary", "📖", "Real Stories", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00426-littledotstudio-realstoriesnz-samsungnz/playlist.m3u8" },
                    { 28, "Nature", "🌿", "Real Wild", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00426-littledotstudio-realwildnz-samsungnz/playlist.m3u8" },
                    { 29, "Kids", "👶", "Ryan and Friends", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00286-pocketwatch-ryanandfriends-samsungnz/playlist.m3u8" },
                    { 30, "Food", "🍽️", "Tastemade International", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00047-tastemade-tmintlaus-samsungnz/playlist.m3u8" },
                    { 31, "Home", "🏠", "The Design Network", "https://thedesignnetwork-tdn-1-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 32, "History", "⏳", "Timeline", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00426-littledotstudio-timelinenz-samsungnz/playlist.m3u8" },
                    { 33, "Sports", "⚽", "Trace Sports Stars 1", "https://trace-sportstars-samsungnz.amagi.tv/playlist.m3u8" },
                    { 34, "Music", "🎵", "Trace Urban", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01076-lightningintern-traceurban-samsungnz/playlist.m3u8" },
                    { 35, "Travel", "✈️", "Travel XP", "https://travelxp-travelxp-1-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 36, "Crime", "🕵️", "TrueCrimeNow", "https://alliantcontent-truecrimenow-3-nz.samsung.wurl.tv/playlist.m3u8" },
                    { 37, "Documentary", "❓", "Wonder", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg00426-littledotstudio-wondernz-samsungnz/playlist.m3u8" },
                    { 38, "Kids", "🦁", "Zoo Moo", "https://cdn-apse1-prod.tsv2.amagi.tv/linear/amg01553-blueantmediaasi-zoomoonz-samsungnz/playlist.m3u8" },
                    { 39, "NZ", "🇳🇿", "Bravo +1", "https://i.mjh.nz/.r/bravo-plus1.m3u8" },
                    { 40, "NZ", "🇳🇿", "Channel 200", "https://d1jlnqid3sfc6m.cloudfront.net/out/v1/3fc2254c865a457c8d7fbbce227a2aae/index.m3u8" },
                    { 41, "NZ", "🇳🇿", "Firstlight", "https://uni01rtmp.tulix.tv/firstlight/firstlight.smil/playlist.m3u8" },
                    { 42, "NZ", "🇳🇿", "Juice TV", "https://juicex.nz/hls/mystream.m3u8" },
                    { 43, "NZ", "🇳🇿", "Kordia TV", "https://ptvlive.kordia.net.nz/out/v1/3fc2254c865a457c8d7fbbce227a2aae/index.m3u8" },
                    { 44, "NZ", "🇳🇿", "Love Stories TV", "https://84e619480232400a842ce499d053458a.mediatailor.us-east-1.amazonaws.com/v1/manifest/04fd913bb278d8775298c26fdca9d9841f37601f/ONO_LoveStoriesTV/18a65393-ba3b-4912-90d5-7188c128ac66/3.m3u8" },
                    { 45, "NZ", "🏛️", "Parliament TV", "https://ptvlive.kordia.net.nz/out/v1/daf20b9a9ec5449dadd734e50ce52b74/index.m3u8" },
                    { 46, "NZ", "🇳🇿", "Sky Open", "https://primetv-prod.akamaized.net/v1/prime-freeview-aes128.m3u8" },
                    { 47, "NZ", "🇳🇿", "Sky Open +1", "https://linear-p.media.skyone.co.nz/primeplus1.clear.m3u8" },
                    { 48, "NZ", "🇳🇿", "Te Reo", "https://i.mjh.nz/.r/te-reo.m3u8" },
                    { 49, "NZ", "📺", "TVNZ 1", "https://d2ce82tpc3p734.cloudfront.net/v1/master/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_1/master.m3u8" },
                    { 50, "NZ", "📺", "TVNZ 2", "https://duoak7vltfob0.cloudfront.net/v1/master/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_2/master.m3u8" },
                    { 51, "NZ", "📺", "TVNZ Duke", "https://dayqb844napyo.cloudfront.net/v1/master/b1f4432f8f95be9e629d97baabfed15b8cacd1f8/TVNZ_Duke/master.m3u8" },
                    { 52, "NZ", "🇳🇿", "Wairarapa TV ", "https://stream1.np.co.nz/WAITVABR/WAITVABR/playlist.m3u8" },
                    { 53, "NZ", "🇳🇿", "Wairarapa TV (Alt)", "https://stream.wairarapatv.co.nz/Broadband_High/playlist.m3u8" },
                    { 54, "NZ", "🇳🇿", "Wairarapa TV ", "https://stream.wairarapatv.co.nz/Cellular_High/playlist.m3u8" },
                    { 55, "NZ", "🌿", "Whakaata Maori", "https://i.mjh.nz/.r/maori-tv.m3u8" },
                    { 56, "Golf", "⚽", "Golf Kingdom", "https://30a-tv.com/feeds/vidaa/golf.m3u8" },
                    { 57, "Sports", "⚽", "ACL Cornhole TV ", "https://1815337252.rsc.cdn77.org/HLS/CORNHOLETV.m3u8" },
                    { 58, "Sports", "⚽", "Abu Dhabi Sports 1 ", "https://vo-live-media.cdb.cdn.orange.com/Content/Channel/AbuDhabiSportsChannel1/HLS/index.m3u8" },
                    { 59, "Sports", "⚽", "Abu Dhabi Sports 2 ", "https://tr-live-route.adm.tcon.hlit.hvds.tv/Content/Channel/AbuDhabiSportsChannel2/DASH/master.mpd" },
                    { 60, "Sports", "⚽", "Adventure Sports TV ", "https://d3rl6ns7c3ilda.cloudfront.net/scheduler/scheduleMaster/438.m3u8" },
                    { 61, "Sports", "⚽", "Alfa Sport  [Not 24/7]", "https://dev.aftermind.xyz/edge-hls/unitrust/alfasports/index.m3u8?token=8TXWzhY3h6jrzqEqx" },
                    { 62, "Sports", "⚽", "Alkass Four ", "https://liveakgr.alkassdigital.net/hls/live/2097037/Alkass4cn/master.m3u8" },
                    { 63, "Sports", "⚽", "Alkass One ", "https://liveakgr.alkassdigital.net/hls/live/2097037/Alkass1mhu/master.m3u8" },
                    { 64, "Sports", "⚽", "Alkass SHOOF ", "https://liveakgr.alkassdigital.net/hls/live/2097037/Alkass6Shoof1/master.m3u8" },
                    { 65, "Sports", "⚽", "Alkass Six ", "https://liveakgr.alkassdigital.net/hls/live/2097037/Alkass6buzat/master.m3u8" },
                    { 66, "Sports", "⚽", "Alkass Three ", "https://liveakgr.alkassdigital.net/hls/live/2097037/Alkass3vak/master.m3u8" },
                    { 67, "Sports", "⚽", "Alkass Two ", "https://liveakgr.alkassdigital.net/hls/live/2097037/Alkass2hef/master.m3u8" },
                    { 68, "Sports", "⚽", "All Sports ", "https://5cf4a2c2512a2.streamlock.net/dgrau/dgrau/playlist.m3u8" },
                    { 69, "Sports", "⚽", "AntenaSport  [Not 24/7]", "https://stream1.antenaplay.ro/as/asrolive1/playlist.m3u8" },
                    { 70, "Sports", "⚽", "Arryadia ", "https://cdn.live.easybroadcast.io/abr_corp/73_arryadia_k2tgcj0/playlist_dvr.m3u8" },
                    { 71, "Sports", "⚽", "Awapa Sports TV  [Not 24/7]", "https://mgv-awapa.akamaized.net/hls/live/2104282/MGV_CHANNEL15/master.m3u8" },
                    { 72, "Sports", "⚽", "Bahrain Sports 1  [Not 24/7]", "https://5c7b683162943.streamlock.net/live/ngrp:sportsone_all/playlist.m3u8" },
                    { 73, "Sports", "⚽", "Bahrain Sports 2  [Not 24/7]", "https://5c7b683162943.streamlock.net/live/ngrp:bahrainsportstwo_all/playlist.m3u8" },
                    { 74, "Combat Sports", "⚽", "Bellator MMA", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/5ebc8688f3697d00072f7cf8/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c26f5a6-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=0e97a69e-3355-4217-b6fb-8952f0ad1803" },
                    { 75, "Billiards", "⚽", "Billiard TV ", "https://1621590671.rsc.cdn77.org/HLS/BILLIARDTV.m3u8" },
                    { 76, "Sports", "⚽", "Blue Sport 2 ", "http://62.210.211.188:2095/play/a00f" },
                    { 77, "Sports", "⚽", "CBS Sports Golazo Network", "https://dai.google.com/linear/hls/event/GxrCGmwST0ixsrc_QgB6qw/master.m3u8" },
                    { 78, "Sports", "⚽", "CBS Sports HQ", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/5e9f2c05172a0f0007db4786/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c27b8f5-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=3a15356b-8467-4ae7-b2f6-9c8467fcf41d" },
                    { 79, "Sports", "⚽", "CBS Sports Network USA", "http://fl2.moveonjoy.com/CBS_SPORTS_NETWORK/index.m3u8" },
                    { 80, "Sports", "⚽", "CDN Deporte ", "https://rtmp-live-ingest-us-east-1-universe-dacast-com.akamaized.net/transmuxv1/streams/bc949011-1dd8-4d10-596c-f6910d4a9cf7.m3u8" },
                    { 81, "Sports", "⚽", "CDR ", "https://live-hls-xgod.livepush.io/live_cdn/emaf6CHYV7M-RQcL2/index.m3u8" },
                    { 82, "Sports", "⚽", "CIS TV ", "http://185.59.221.131:8081/live/cistv/playlist.m3u8" },
                    { 83, "Sports", "⚽", "CampusLore ", "https://linear-235.frequency.stream/dist/glewedtv/235/hls/master/playlist.m3u8" },
                    { 84, "Sports", "⚽", "Canal+ Sport", "http://78.130.250.2:8023/play/a02v/index.m3u8" },
                    { 85, "Sports", "⚽", "Champion TV ", "https://canal.mediaserver.com.co/live/ChampionTv.m3u8" },
                    { 86, "Sports", "⚽", "Claro Sports Chile", "https://stitcher-ipv4.pluto.tv/v1/stitch/embed/hls/channel/6320d80a66666000086712d7livestitch/master.m3u8?advertisingId={PSID}&appVersion=unknown&deviceDNT={TARGETOPT}&deviceId={PSID}&deviceLat=0&deviceLon=0&deviceMake=samsung&deviceModel=samsung&deviceType=samsung-tvplus&deviceVersion=unknown&embedPartner=samsung-tvplus&profileFloor=&profileLimit=&profilesFromStream=true&samsung_app_domain={APP_DOMAIN}&samsung_app_name={APP_NAME}&us_privacy=1YNY" },
                    { 87, "Sports", "⚽", "ColimdoT TV ", "https://cnn.livestreaminggroup.info:3132/live/colimdotvlive.m3u8" },
                    { 88, "Combat Sports", "⚽", "Combate Global", "https://stream.ads.ottera.tv/playlist.m3u8?network_id=960" },
                    { 89, "Sports", "⚽", "Contacto Deportivo  [Not 24/7]", "https://live.obslivestream.com/cdeportivo/index.m3u8" },
                    { 90, "Sports", "⚽", "ČT Sport ", "http://88.212.15.19/live/test_ctsport_25p/playlist.m3u8" },
                    { 91, "Motorsports", "⚽", "DF1 ", "https://dbjwcot8t7nyd.cloudfront.net/out/v1/9d068a9428444b458324ad77b5a0a4b8/index.m3u8" },
                    { 92, "Motorsports", "⚽", "Dubai Racing ", "https://dmisdracta.cdn.mgmlcdn.com/events/smil:events.stream.smil/chunklist.m3u8" },
                    { 93, "Motorsports", "⚽", "Dubai Racing 2 ", "https://dmithrvllta.cdn.mgmlcdn.com/dubairacing/smil:dubairacing.smil/chunklist.m3u8" },
                    { 94, "Motorsports", "⚽", "Dubai Racing 3 ", "https://dmithrvllta.cdn.mgmlcdn.com/dubaimubasher/smil:dubaimubasher.smil/chunklist.m3u8" },
                    { 95, "Sports", "⚽", "Dubai Sports 1 ", "https://dmidspta.cdn.mgmlcdn.com/dubaisports/smil:dubaisports.stream.smil/chunklist.m3u8" },
                    { 96, "Sports", "⚽", "Dubai Sports 2 ", "https://dmitwlvvll.cdn.mgmlcdn.com/dubaisportshd/smil:dubaisportshd.smil/chunklist.m3u8" },
                    { 97, "Sports", "⚽", "Dubai Sports 3  [Not 24/7]", "https://dmitwlvvll.cdn.mgmlcdn.com/dubaisportshd5/smil:dubaisportshd5.smil/chunklist.m3u8" },
                    { 98, "Sports", "⚽", "EDGEsport ", "https://edgesport-samsunguk.amagi.tv/playlist.m3u8" },
                    { 99, "Sports", "⚽", "ERT Sports 1 ", "http://hbbtvapp.ert.gr/stream.php/v/vid_ertsports_mpeg.2ts" },
                    { 100, "Sports", "⚽", "ERT Sports 2 ", "http://hbbtvapp.ert.gr/stream.php/v/vid_ertplay2_mpeg.2ts" },
                    { 101, "Sports", "⚽", "ESPN U ", "http://fl2.moveonjoy.com/ESPN_U/index.m3u8" },
                    { 102, "Sports", "⚽", "ESPNews ", "http://fl2.moveonjoy.com/ESPN_NEWS/index.m3u8" },
                    { 103, "eSports", "⚽", "ESR 24x7 eSports Network ", "https://eyeonesports.com/ES2RA-628g.m3u8" },
                    { 104, "eSports", "⚽", "ESTV ", "https://estv-rakuten-samsung.amagi.tv/playlist.m3u8" },
                    { 105, "eSports", "⚽", "Egg Network ", "http://210.210.155.37/uq2663/h/h22/index.m3u8" },
                    { 106, "Sports", "⚽", "Eleven Sports 1 (2160p)", "http://9b129915.akadatel.com/iptv/83GA6FAV4DPTPQ/20068/index.m3u8" },
                    { 107, "Sports", "⚽", "Eleven Sports 2 ", "http://109.233.89.166/Eleven_Sports_2_HD/index.m3u8" },
                    { 108, "Sports", "⚽", "Eleven Sports 3 ", "http://109.233.89.166/Eleven_Sports_3_HD/index.m3u8" },
                    { 109, "Sports", "⚽", "Eleven Sports 4 ", "http://109.233.89.166/ELEVEN_SPORTS_4_HD/index.m3u8" },
                    { 110, "Sports", "⚽", "FL Sport ", "https://tvsw5-hls.secdn.net/tvsw5-chorigin/play/prod-8ce1fcb47fa7474d84640eb766f0ef38/playlist.m3u8" },
                    { 111, "Sports", "⚽", "FTV ", "https://master.tucableip.com/ftv/index.m3u8" },
                    { 112, "Football", "⚽", "FUTV Costa Rica ", "http://45.190.187.226:58092/play/a00q" },
                    { 113, "Sports", "⚽", "Fast Sports", "http://stream01.vnet.am/Channel_131/index.m3u8" },
                    { 114, "Combat Sports", "⚽", "Fight", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/5812b0f2237a6ff45d16c3f9/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c28ca64-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=5722f4bc-fbe1-409f-ad8f-4559e5ebda2f" },
                    { 115, "Combat Sports", "⚽", "Fight Klub)", "http://185.236.229.62:9981/play/a02l" },
                    { 116, "Combat Sports", "⚽", "Fight Network", "https://d12a2vxqkkh1bo.cloudfront.net/hls/main.m3u8" },
                    { 117, "Combat Sports", "⚽", "Fight Night ", "https://origin3.afxp.telemedia.co.za/PremiumFree/fightnight/playlist.m3u8" },
                    { 118, "Combat Sports", "⚽", "FightBox", "http://stream01.vnet.am/Fightbox/mono.m3u8" },
                    { 119, "Combat Sports", "⚽", "Fite  [Not 24/7]", "https://cdn-cf.fite.tv/linear/fite247/playlist.m3u8" },
                    { 120, "Combat Sports", "⚽", "FITE 24/7 ", "https://d3d85c7qkywguj.cloudfront.net/scheduler/scheduleMaster/263.m3u8" },
                    { 121, "Sports", "⚽", "Fox Sports en Espanol ", "https://apollo.production-public.tubi.io/live/fox-sports-espanol.m3u8" },
                    { 122, "Motorsports", "⚽", "FUEL TV ", "https://amg01074-fueltv-fueltvemeaen-rakuten-b6j62.amagi.tv/hls/amagi_hls_data_rakutenAA-fueltvemeaen/CDN/master.m3u8" },
                    { 123, "Football", "⚽", "Futbol ", "https://live.teleradiocom.tj/8/3m.m3u8" },
                    { 124, "eSports", "⚽", "Game Channel", "http://49.113.179.174:4022/udp/238.125.1.36:5140" },
                    { 125, "Sports", "⚽", "Game+ ", "https://a-cdn.klowdtv.com/live2/fntsy_720p/playlist.m3u8" },
                    { 126, "Sports", "⚽", "Gaora Sports (544p)", "http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=cs17&isp=4" },
                    { 127, "Combat Sports", "⚽", "Glory Kickboxing ", "https://6f972d29.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWV1X0dsb3J5S2lja2JveGluZ19ITFM/playlist.m3u8" },
                    { 128, "Golf", "⚽", "Golf Channel", "http://fl2.moveonjoy.com/GOLF_CHANNEL/index.m3u8" },
                    { 129, "Golf", "⚽", "Golf Channel ", "http://185.236.229.62:9981/play/a03m" },
                    { 130, "Golf", "⚽", "Golf Network (540p)", "http://202.60.106.14:8080/1335/playlist.m3u8" },
                    { 131, "Sports", "⚽", "HTSpor TV ", "http://185.234.111.229:8000/play/a016" },
                    { 132, "Combat Sports", "⚽", "Hard Knocks  [Not 24/7]", "https://d3uyzhwvmemdyf.cloudfront.net/v1/master/9d062541f2ff39b5c0f48b743c6411d25f62fc25/HardKnocks-SportsTribal/121.m3u8" },
                    { 133, "Horse Racing", "⚽", "HorseTV ", "https://a-cdn.klowdtv.com/live2/horsetv_720p/playlist.m3u8" },
                    { 134, "Combat Sports", "⚽", "IMPACT Plus! ", "https://d2tuwvs0ja335j.cloudfront.net/hls/main.m3u8" },
                    { 135, "Sports", "⚽", "Idman TV", "https://str.yodacdn.net/idman/index.m3u8" },
                    { 136, "Sports", "⚽", "Insight TV ", "https://insighttv-samsungau.amagi.tv/playlist.m3u8" },
                    { 137, "Sports", "⚽", "K19", "https://1853185335.rsc.cdn77.org/K192/tv/playlist.m3u8" },
                    { 138, "Motorsports", "⚽", "KCMN-LD6 ", "https://cdn-uw2-prod.tsv2.amagi.tv/linear/amg02873-kravemedia-mtrspt1-distrotv/playlist.m3u8" },
                    { 139, "Sports", "⚽", "KTV Sport ", "https://kwtspta.cdn.mangomolo.com/sp/smil:sp.stream.smil/chunklist.m3u8" },
                    { 140, "Sports", "⚽", "KTV Sport Plus ", "https://kwtsplta.cdn.mangomolo.com/spl/smil:spl.stream.smil/chunklist.m3u8" },
                    { 141, "Billiards", "⚽", "Kozoom TV", "https://streams2.sofast.tv/v1/master/611d79b11b77e2f571934fd80ca1413453772ac7/fdd6f243-f971-4a1a-9510-97ac01d6b37f/manifest.m3u8" },
                    { 142, "Sports", "⚽", "L'Equipe", "https://raw.githubusercontent.com/ipstreet312/freeiptv/master/ressources/dmotion/py/eqpe/equipe.m3u8" },
                    { 143, "Sports", "⚽", "Lacrosse TV ", "https://1840769862.rsc.cdn77.org/FTF/LSN_SCTE.m3u8" },
                    { 144, "Horse Racing", "⚽", "Lóverseny közvetítés (420p)", "http://87.229.103.60:1935/liverelay/loverseny2.sdp/playlist.m3u8" },
                    { 145, "Motorsports", "⚽", "MAV Select USA", "https://d3h07n6l1exhds.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/cc-0z2yyo4dxctc7/playlist.m3u8" },
                    { 146, "Baseball", "⚽", "MLB Network", "http://fl2.moveonjoy.com/MLB_NETWORK/index.m3u8" },
                    { 147, "Sports", "⚽", "MNB Sport ", "https://cdn3.skygo.mn/live/disk1/MNBSport/DASH-FTA/MNBSport.mpd" },
                    { 148, "Sports", "⚽", "MSG", "http://fl3.moveonjoy.com/MSG/index.m3u8" },
                    { 149, "Sports", "⚽", "MSG Plus ", "https://tvpass.org/live/msg-plus/hd" },
                    { 150, "Football", "⚽", "MUTV ", "https://bcovlive-a.akamaihd.net/r2d2c4ca5bf57456fb1d16255c1a535c8/eu-west-1/6058004203001/playlist.m3u8" },
                    { 151, "Sports", "⚽", "MadeinBO TV ", "https://srvx1.selftv.video/dmchannel/live/playlist.m3u8" },
                    { 152, "Horse Racing", "⚽", "Monterrico TV  [Not 24/7]", "https://ed3od.live.opencaster.com/jcpstream_hd720/index.m3u8" },
                    { 153, "Sports", "⚽", "More Than Sports TV ", "https://mts1.iptv-playoutcenter.de/mts/mts-web/playlist.m3u8" },
                    { 154, "Motorsports", "⚽", "Motorsport.tv ", "https://9e2ee5d5.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWV1X01vdG9yc3BvcnR0dl9ITFM/playlist.m3u8" },
                    { 155, "Sports", "⚽", "Multivisión Sports  [Not 24/7]", "https://stream.digitalgt.com:3605/live/multivisionsportslive.m3u8" },
                    { 156, "Motorsports", "⚽", "NHRA TV ", "https://apollo.production-public.tubi.io/live/ac-nhra.m3u8" },
                    { 157, "Sports", "⚽", "NHL", "https://nhl-firetv.amagi.tv/playlist.m3u8" },
                    { 158, "Sports", "⚽", "NTV Spor", "http://46.4.193.238:8484/hls/ntvspor/playlist.m3u8" },
                    { 159, "Sports", "⚽", "Nautical Channel ", "https://a-cdn.klowdtv.com/live2/nautical_720p/playlist.m3u8" },
                    { 160, "Sports", "⚽", "NBC Sports Bay Area", "https://v1.thetvapp.to/hls/nbc-sports-bay-area/index.m3u8" },
                    { 161, "Sports", "⚽", "NBC Sports Boston", "https://v1.thetvapp.to/hls/nbc-sports-boston/index.m3u8" },
                    { 162, "Sports", "⚽", "NBC Sports Philadelphia", "https://v1.thetvapp.to/hls/nbc-sports-philadelphia/index.m3u8" },
                    { 163, "Football", "⚽", "NFL Channel", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/5ced7d5df64be98e07ed47b6/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c2a5105-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=6477ef85-3680-442c-94d8-27197903b1f6" },
                    { 164, "Football", "⚽", "NFL Network", "http://fl2.moveonjoy.com/NFL_NETWORK/index.m3u8" },
                    { 165, "Football", "⚽", "NFL RedZone", "http://fl1.moveonjoy.com/NFL_RedZone/index.m3u8" },
                    { 166, "Sports", "⚽", "Nittele G Plus (544p)", "http://cdns.jp-primehome.com:8000/zhongying/live/playlist.m3u8?cid=cs02&isp=4" },
                    { 167, "Football", "⚽", "OMONOIA TV (684p)", "http://62.233.57.226:8001/play/a00b00" },
                    { 168, "Sports", "⚽", "Oman Sports TV  [Not 24/7]", "https://partneta.cdn.mgmlcdn.com/omsport/smil:omsport.stream.smil/chunklist.m3u8" },
                    { 169, "Golf", "⚽", "One Golf ", "http://162.250.201.58:6211/pk/ONEGOLF/index.m3u8" },
                    { 170, "Sports", "⚽", "Ovacion TV  [Not 24/7]", "http://cdn2.ujjina.com:1935/iptvovacion1/liveovacion1tv/playlist.m3u8" },
                    { 171, "Sports", "⚽", "PBR RidePass", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/60d39387706fe50007fda8e8/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c2a9f21-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=f7275d4e-aa8e-4e8d-9d5e-6a5665bf8190" },
                    { 172, "Golf", "⚽", "PGA Tour", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/5de94dacb394a300099fa22a/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c2ac630-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=6c2b7359-0375-4f34-996b-4fb9429ead78" },
                    { 173, "Sports", "⚽", "PTV Sports", "http://121.91.61.106:8000/play/a00l/index.m3u8" },
                    { 174, "Sports", "⚽", "Pac12 Insider ", "https://pac12-sportstribal.amagi.tv/playlist.m3u8" },
                    { 175, "Sports", "⚽", "Persiana Sport", "https://persiana.mastercast.cloud/memfs/f1accec0-3b52-476b-ada9-65f74ead985e.m3u8" },
                    { 176, "Sports", "⚽", "Pluto TV Deportes ", "https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5dcde07af1c85b0009b18651/master.m3u8?advertisingId=&appName=web&appVersion=5.14.0-0f5ca04c21649b8c8aad4e56266a23b96d73b83a&app_name=web&clientDeviceType=0&clientID=6fbead95-26b1-415d-998f-1bdef62d10be&clientModelNumber=na&deviceDNT=false&deviceId=6fbead95-26b1-415d-998f-1bdef62d10be&deviceLat=19.4358&deviceLon=-99.1441&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=88.0.4324.150&marketingRegion=VE&serverSideAds=false&sessionID=b8e5a857-714a-11eb-b532-0242ac110002&sid=b8e5a857-714a-11eb-b532-0242ac110002&userId=" },
                    { 177, "Combat Sports", "⚽", "Pluto TV Lucha Libre AAA ", "https://service-stitcher.clusters.pluto.tv/stitch/hls/channel/5c01df1759ee03633e7b272c/master.m3u8?advertisingId=&appName=web&appStoreUrl=&appVersion=DNT&app_name=&architecture=&buildVersion=&deviceDNT=0&deviceId=5c01df1759ee03633e7b272c&deviceLat=&deviceLon=&deviceMake=web&deviceModel=web&deviceType=web&deviceVersion=DNT&includeExtendedEvents=false&marketingRegion=US&serverSideAds=false&sid=971&terminate=false&userId=" },
                    { 178, "Sports", "⚽", "Pluto TV Sports", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/56340779a738201b4ccfeac9/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c2b3b63-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=8673a43c-58ba-48b3-8db5-75986abb01b9" },
                    { 179, "Poker", "⚽", "Poker Night in America ", "https://d2njbreu8qyfxo.cloudfront.net/scheduler/scheduleMaster/216.m3u8" },
                    { 180, "Poker", "⚽", "Poker TV ", "https://hls.pokertvfa.live/hls/stream.m3u8" },
                    { 181, "Poker", "⚽", "PokerGo", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/5fc54366b04b2300072e31af/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c2b6274-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=a68d07ef-a794-43f8-a287-3bd7f27d909b" },
                    { 182, "Sports", "⚽", "Polsat Sport ", "http://109.233.89.170/Polsat_Sport_HD/index.m3u8" },
                    { 183, "Sports", "⚽", "Polsat Sport Extra ", "http://109.233.89.170/Polsat_Sport_Extra_HD/index.m3u8" },
                    { 184, "Combat Sports", "⚽", "Polsat Sport Fight ", "http://109.233.89.170/Polsat_Sport_Fight_HD/index.m3u8" },
                    { 185, "Sports", "⚽", "RTA Sport ", "https://rtatv.akamaized.net/Content/HLS/Live/channel(RTA3)/index.m3u8" },
                    { 186, "Sports", "⚽", "RTI La 3  [Not 24/7]", "https://www.enovativecdn.com/rticdn/smil:rti3.smil/playlist.m3u8" },
                    { 187, "Motorsports", "⚽", "Racing America ", "https://livetv-fa.tubi.video/racing-america/playlist.m3u8" },
                    { 188, "Horse Racing", "⚽", "Racing.com ", "https://racingvic-i.akamaized.net/hls/live/598695/racingvic/index1500.m3u8" },
                    { 189, "Football", "⚽", "Real Madrid TV (404p)", "https://rmtv.akamaized.net/hls/live/2043153/rmtv-es-web/master.m3u8" },
                    { 190, "Sports", "⚽", "Realitatea Sportivă ", "https://stream.realitatea.net/realitatea/sportiva_md/playlist.m3u8" },
                    { 191, "Sports", "⚽", "Red Bull TV ", "https://3ea22335.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/UmFrdXRlblRWLWdiX1JlZEJ1bGxUVl9ITFM/playlist.m3u8" },
                    { 192, "Sports", "⚽", "RightNow TV ", "https://a-cdn.klowdtv.com/live2/rightnowtv_720p/playlist.m3u8" },
                    { 193, "Sports", "⚽", "S Sport", "https://bcovlive-a.akamaihd.net/540fcb034b144b848e7ff887f61a293a/eu-central-1/6415845530001/profile_0/chunklist.m3u8" },
                    { 194, "Sports", "⚽", "S Sport 2", "https://bcovlive-a.akamaihd.net/29c60f23ea4840ba8726925a77fcfd0b/eu-central-1/6415845530001/profile_0/chunklist.m3u8" },
                    { 195, "Sports", "⚽", "SEO TV 5 Deportes  [Not 24/7]", "https://seo.tv.bo/tv/SEOtv_5sd.m3u8" },
                    { 196, "Sports", "⚽", "SKI TV  [Not 24/7]", "https://d2xeo83q8fcni6.cloudfront.net/v1/master/9d062541f2ff39b5c0f48b743c6411d25f62fc25/SkiTV-SportsTribal/193.m3u8" },
                    { 197, "Football", "⚽", "SMG Football Channel", "http://49.113.179.174:4022/udp/238.125.2.142:5140" },
                    { 198, "Sports", "⚽", "SOS Kanal Plus ", "https://53be5ef2d13aa.streamlock.net/soskanalplus/soskanalplus.stream/playlist.m3u8" },
                    { 199, "Sports", "⚽", "SSC Action Waleed  [Not 24/7]", "https://shls-live-event2-prod-dub.shahid.net/out/v1/0456ede1a39145d98b3d8c8062ddc998/index.m3u8" },
                    { 200, "Sports", "⚽", "San Marino RTV Sport ", "https://d2hrvno5bw6tg2.cloudfront.net/smrtv-ch02/smil:ch-02.smil/master.m3u8" },
                    { 201, "Sports", "⚽", "Sharjah Sports TV ", "https://svs.itworkscdn.net/smc4sportslive/smc4.smil/playlist.m3u8" },
                    { 202, "Sports", "⚽", "Sony Six HD ", "http://103.81.104.118/hls/stream10.m3u8" },
                    { 203, "Sports", "⚽", "Sport En France ", "https://sp1564435593.mytvchain.info/live/sp1564435593/index.m3u8" },
                    { 204, "Football", "⚽", "Sportitalia SoloCalcio", "https://di-g7ij0rwh.vo.lswcdn.net/sportitalia/sisolocalcio.smil/playlist.m3u8" },
                    { 205, "Sports", "⚽", "Sports Connect ", "https://origin3.afxp.telemedia.co.za/PremiumFree/sportsconnect/playlist.m3u8" },
                    { 206, "Sports", "⚽", "SportsGrid ", "https://sportsgrid-tribal.amagi.tv/playlist.m3u8" },
                    { 207, "Sports", "⚽", "SportsNet New York (540p)", "http://fl2.moveonjoy.com/SNY/index.m3u8" },
                    { 208, "Sports", "⚽", "Sportsman Channel", "http://fl2.moveonjoy.com/SPORTSMAN_CHANNEL/index.m3u8" },
                    { 209, "Sports", "⚽", "Stadium ", "https://apollo.production-public.tubi.io/live/ac-stadium2.m3u8" },
                    { 210, "Sports", "⚽", "Swerve Sports ", "https://linear-253.frequency.stream/dist/glewedtv/253/hls/master/playlist.m3u8" },
                    { 211, "Sports", "⚽", "T Sports 7 ", "https://lb1-live-mv.v2h-cdn.com/hls/ffef/tsport/tsport.m3u8" },
                    { 212, "Sports", "⚽", "TDM Sports Ch. 93 ", "https://live3.tdm.com.mo/ch4/sport_ch4.live/playlist.m3u8" },
                    { 213, "Combat Sports", "⚽", "TNA Wrestling ", "https://d3mwqwqfak7y2q.cloudfront.net/v1/master/3722c60a815c199d9c0ef36c5b73da68a62b09d1/ImpactWrestling-prod/hls/main.m3u8" },
                    { 214, "Sports", "⚽", "TR Sport ", "https://livetr.teleromagna.it/mia/live/playlist.m3u8" },
                    { 215, "Sports", "⚽", "TRT Spor ", "http://185.234.111.229:8000/play/a00e" },
                    { 216, "Sports", "⚽", "TSN1 ", "http://fl5.moveonjoy.com/TSN_1/index.m3u8" },
                    { 217, "Sports", "⚽", "TSN2", "http://fl5.moveonjoy.com/TSN_2/index.m3u8" },
                    { 218, "Sports", "⚽", "TSN3", "http://fl5.moveonjoy.com/TSN_3/index.m3u8" },
                    { 219, "Sports", "⚽", "TSN4", "http://fl5.moveonjoy.com/TSN_4/index.m3u8" },
                    { 220, "Sports", "⚽", "TSN5", "http://fl5.moveonjoy.com/TSN_5/index.m3u8" },
                    { 221, "Sports", "⚽", "TV 2 Sport 1 ", "https://ws31-hls-live.akamaized.net/out/u/1416253.m3u8" },
                    { 222, "Combat Sports", "⚽", "TVMatic Fight ", "http://cdn.tvmatic.net/fight.m3u8" },
                    { 223, "Sports", "⚽", "TVP Sport ", "http://109.233.89.166/TVP_Sport_HD/index.m3u8" },
                    { 224, "Sports", "⚽", "TVQ Sports ", "https://dacastmmd.mmdlive.lldns.net/dacastmmd/1b6bbade53634f5a847b953c9adfd102/index.m3u8" },
                    { 225, "Sports", "⚽", "TVRI Sport ", "https://ott-balancer.tvri.go.id/live/eds/SportHD/hls/SportHD.m3u8" },
                    { 226, "Bowling", "⚽", "TVS Bowling Network ", "https://bozztv.com/gusa/gusa-tvsbowling/index.m3u8" },
                    { 227, "Combat Sports", "⚽", "TVS Boxing ", "https://bozztv.com/gusa/gusa-tvsboxing/index.m3u8" },
                    { 228, "Sports", "⚽", "TVS Classic Sports ", "https://bozztv.com/gusa/gusa-tvs/index.m3u8" },
                    { 229, "Sports", "⚽", "TVS Sports  [Not 24/7]", "https://bozztv.com/gusa/gusa-tvssports/index.m3u8" },
                    { 230, "Sports", "⚽", "TVS Sports Bureau ", "https://bozztv.com/gusa/gusa-tvssportsbureau/index.m3u8" },
                    { 231, "Motorsports", "⚽", "TVS Turbo ", "https://bozztv.com/gusa/gusa-tvsturbo/index.m3u8" },
                    { 232, "Sports", "⚽", "TVS Women Sports ", "https://bozztv.com/gusa/gusa-tvswsn/index.m3u8" },
                    { 233, "Sports", "⚽", "talkSPORT ", "https://af7a8b4e.wurl.com/master/f36d25e7e52f1ba8d7e56eb859c636563214f541/TEctZ2JfdGFsa1NQT1JUX0hMUw/playlist.m3u8" },
                    { 234, "Horse Racing", "⚽", "Teletrak ", "https://unlimited6-cl.dps.live/sportinghd/sportinghd.smil/playlist.m3u8" },
                    { 235, "Sports", "⚽", "Ten Sports Pakistan", "http://121.91.61.106:8000/play/a04h/index.m3u8" },
                    { 236, "Sports", "⚽", "Tennis Channel", "https://cdn-ue1-prod.tsv2.amagi.tv/linear/amg01444-tennischannelth-tennischannelnl-samsungnl/playlist.m3u8" },
                    { 237, "Sports", "⚽", "Tigo Sports (Costa Rica)", "https://acceso.radiosportstv.online:3795/stream/play.m3u8" },
                    { 238, "Sports", "⚽", "Tigo Sports (Guatemala)", "https://cnm-tsl.otteravision.com/cnm/tsl/tsl.m3u8" },
                    { 239, "Sports", "⚽", "Trace Sport Stars (Australia) ", "https://lightning-tracesport-samsungau.amagi.tv/playlist.m3u8" },
                    { 240, "Sports", "⚽", "Trace Sports Stars", "https://trace-sportstars-samsungnz.amagi.tv/playlist.m3u8" },
                    { 241, "Horse Racing", "⚽", "Turf Movil ", "https://tvturf4.janus.cl/playlist/stream.m3u8?d=w&id=" },
                    { 242, "Football", "⚽", "UD Las Palmas TV  [Not 24/7]", "https://cdn318.fractalmedia.es/live319/hls/cudtv/high/index.m3u8" },
                    { 243, "Sports", "⚽", "Unbeaten ", "https://unbeaten-tcl.amagi.tv/playlist.m3u8" },
                    { 244, "Sports", "⚽", "V Sport Vinter ", "http://62.210.211.188:2095/play/a00q" },
                    { 245, "Sports", "⚽", "Vinx TV ", "https://tv.radiocast.es:5443/vinxtv/streams/vinxtvlive.m3u8" },
                    { 246, "Sports", "⚽", "W14DK-D 14.5 All Sports Television Network", "https://2-fss-2.streamhoster.com/pl_118/204972-2205186-1/playlist.m3u8" },
                    { 247, "Poker", "⚽", "World Poker Tour", "https://world-poker-tour-samsung-ca.samsung.wurl.tv/playlist.m3u8" },
                    { 248, "Sports", "⚽", "World of Freesports ", "https://mainstreammedia-worldoffreesportsintl-rakuten.amagi.tv/hls/amagi_hls_data_rakutenAA-mainstreammediafreesportsintl-rakuten/CDN/master.m3u8" },
                    { 249, "Sports", "⚽", "Zoy TV Sports 1", "https://fl1004.bozztv.com/ssh101/zoytvsports/index.m3u8" },
                    { 250, "Sports", "⚽", "Zoy TV Sports 2", "https://fl1004.bozztv.com/ssh101/zoytvsports2/index.m3u8" },
                    { 251, "Sports", "⚽", "Zoy TV Sports 3", "https://fl1004.bozztv.com/ssh101/zoytvsports3/index.m3u8" },
                    { 252, "Sports", "⚽", "Zoy TV Sports 4", "https://fl1004.bozztv.com/ssh101/zoytvsports4/index.m3u8" },
                    { 253, "Sports", "⚽", "Zoy TV Sports 5", "https://fl1004.bozztv.com/ssh101/zoytvsports5/index.m3u8" },
                    { 254, "Sports", "⚽", "beIN Sports Haber", "https://canlitvulusal3.xyz/live/beinsportshaber/index.m3u8" },
                    { 255, "Sports", "⚽", "beIN SPORTS XTRA", "http://cfd-v4-service-channel-stitcher-use1-1.prd.pluto.tv/stitch/hls/channel/5df975e2b27cf5000921c102/master.m3u8?appName=web&appVersion=unknown&clientTime=0&deviceDNT=0&deviceId=6c26f5a4-30d3-11ef-9cf5-e9ddff8ff496&deviceMake=Chrome&deviceModel=web&deviceType=web&deviceVersion=unknown&includeExtendedEvents=false&serverSideAds=false&sid=cb932046-e001-4189-a871-1376aa2ec340" },
                    { 256, "Sports", "⚽", "viju+ Sport", "http://stream1.cinerama.uz/1229/tracks-v1a1/mono.m3u8" }
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Channels");
        }
    }
}
